### ISSUE TITLE
Отчетнось

### ISSUE THREAD

**Issue by zzanya** [zzanya/virtual_museum#20]
### Подзадачи
- [x] [#10 Подготовить и предоставить отчетность по запросу преподавателя](https://github.com/zzanya/virtual_museum/issues/10)
- [x] [#9 Изучить технологию для отслеживания задач и прогресса проекта](https://github.com/zzanya/virtual_museum/issues/9)
- [x] [#19 Настроить GitHub Team Planning и предоставить доступ команде](https://github.com/zzanya/virtual_museum/issues/19)
- [x] [#14 Добавь возможность размещения подзадачи для большей задачи](https://github.com/zzanya/virtual_museum/issues/14)
- [x] [#27 Обновление подзадач](https://github.com/zzanya/virtual_museum/issues/27)
