### ISSUE TITLE
Исправление ошибок и багов.

### ISSUE THREAD

**Issue by zzanya** [zzanya/virtual_museum#7]
## Подзадачи:
- [x] [#21 Отслеживание касания](https://github.com/zzanya/virtual_museum/issues/21)
- [x] [#22 Движение относительно персонажа](https://github.com/zzanya/virtual_museum/issues/22)
- [x] [#23 Дергание джойстика на около максимальных значениях](https://github.com/zzanya/virtual_museum/issues/23)
- [x] [#24 Перекрытие интерфейса, элементами локации](https://github.com/zzanya/virtual_museum/issues/24)
- [x] [#25 Некорректное вращение объекта](https://github.com/zzanya/virtual_museum/issues/25)
